bugfix: fixes expansion infinite loop on new runs
cmu-sei/Caster.Ui pull request #125
Opened 2021-04-02 19:19 UTC by sei-noconnor

- bind cwd-table component in trackBy function
- revert expandRun function on workspace service
- ensure signalR connection on run component plan and apply
- shareReplayConfig added to workspace container component.

2021-04-02 19:22 UTC, sei-aschlackman approved these changes

2021-04-02 19:43 UTC, sei-ebram requested changes
I'll approve after the LGTM result is fixed!

2021-04-03 12:44 UTC, sei-ebram approved these changes

2021-04-03 12:48 UTC, merged

2021-04-05 14:22 UTC, sei-rreeder commented
I checked in with Nic. Jira issue for this is [CRU-1827](https://issues.sei.cmu.edu/jira/browse/CRU-1827).